- name: Update dnf cache.
  ansible.builtin.dnf:
    update_cache: true
  become: true

- name: Install dependencies.
  ansible.builtin.package:
    name:
      - '@Development Tools'
      - gcc-gfortran
      # Fedora, at least Fedora Server, doesn't install this 
      # with the Development Tools group for some reason
      - gcc-g++
    state: present
  become: true